### PR TITLE
[WIP] Update for new Lab Extension handling

### PR DESCRIPTION
**Pull request by blink1073**
cf https://github.com/jupyterlab/jupyterlab/pull/2038

image

### CODE REVIEW

**Comment by gnestor** [comment]
@blink1073 Is this still relevant given https://github.com/jupyterlab/jupyterlab/issues/2011#issuecomment-293118232?

If so, I'm having trouble building the labextension:

```
TypeError: build is not a function
    at Object.<anonymous> (/Users/grant/Sites/jupyter/jupyterlab_geojson/labextension/build_extension.js:4:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

**Comment by blink1073** [comment]
I'm currently using this to test against https://github.com/jupyterlab/jupyterlab/pull/2038.

**Comment by gnestor** [comment]
How do you test against these lerna packages? Normally, you would `npm link [package-name]`, but this seems different... 🤔

**Comment by blink1073** [comment]
The previous test I did was against the released versions of JupyterLab.  I just ran the test below and that worked as well.  Can you think of a good way to capture these commands?  Perhaps `jupyterlab linkify` that does all this linking, but only if they're not already symlinked?

```
cd jupyterlab_geojson/labextension
npm link <all the jupyterlab paths>   
cd <virtualenv>/share/jupyter/lab
npm link <all the jupyterlab paths>
npm link <path to jupyterlab_geojson>
```

Could be `jupyterlab linkify <jupyterlab_geojson path>` or `jupyterlab linkify` from that directory.

**Comment by blink1073** [comment]
cc @jasongrout

**Comment by blink1073** [comment]
cc @ian-r-rose

**Comment by gnestor** [comment]
Ok, so you are linking the extension into the jupyterlab directory 👌 

The first thought that comes to mind is Atom's `apm link` which is run in the plugin directory and `npm links` it in the atom directory. It seems like this would work well for jupyterlab: Just run `jupyterlab link` in the extension directory.

**Comment by gnestor** [comment]
@blink1073 I'm running into the "No provider for: jupyter.services.rendermime." error for rendermime, document-registry, and layout-restorerer when trying to install this branch:

```
Plugin 'jupyter.extensions.GeoJSON' failed to activate.    index.js:267 
Error: No provider for: jupyter.services.rendermime.    index.js:268
    at JupyterLab.Application.resolveRequiredService  
 (http://localhost:8888/lab/main.bundle.js:119907:35)
    at Array.map (native)
    at JupyterLab.Application.activatePlugin (http://localhost:8888/lab/main.bundle.js:119865:38)
    at http://localhost:8888/lab/main.bundle.js:119991:26
    at Array.map (native)
    at JupyterLab.Application.start (http://localhost:8888/lab/main.bundle.js:119990:33)
    at main (http://localhost:8888/lab/main.bundle.js:96397:9)
```

Can you give this a try when you're back in the cockpit? To reproduce:

* Checkout jupyterlab 0.20.2: `git checkout v0.20.2`
* Do a git clean:`git clean -xfd` 
* Install: `pip install -e .`
* Install the extension from the labextensions directory: `npm install`
* Link the extension from the labextensions directory: `jupyter labextension link .`

**Comment by jasongrout** [comment]
@gnestor, it looks like you haven't updated your dependencies to match JupyterLab. Can you make *sure* that your JupyterLab and Phosphor dependencies match the versions in JLab 0.20.2?

**Comment by jasongrout** [comment]
(i.e., these ones: https://github.com/jupyterlab/jupyterlab/blob/v0.20.2/jupyterlab/package.json)

**Comment by gnestor** [comment]
I had tried updating the versions (in a different extension) but I didn't notice that the package names changed (e.g. `@jupyterlab/rendermime` to `@jupyterlab/rendermime-extension`)! It's working now :+1:

**Comment by blink1073** [comment]
Both of those packages exist.  The main entry point file linked above only depends on the things it imports directly.

**Pull request closed without merging**
