### PR TITLE
Support both lab and notebook

### PR DESCRIPTION
**Pull request by gnestor**
Rewritten using [mimerender-cookiecutter](https://github.com/jupyterlab/mimerender-cookiecutter/tree/react). Tested and working in both notebook 4.3 and lab 0.12.1.

### CODE REVIEW

**Comment by fperez** [comment]
Quick note in case you hadn't seen it, the PR is failing a test... Would love to see this working across classic/lab, thx!!

**Comment by gnestor** [comment]
@jasongrout The build is failing with:

```
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
The command "rake" exited with 1.
```

Is this because Travis is not set up?

**Comment by jasongrout** [comment]
It looks like it. I think the relevant error is `Could not find .travis.yml, using standard configuration.`.

Are there tests that Travis is supposed to run?

**Comment by gnestor** [comment]
@jasongrout Nope, I don't think any tests are set up for this repo. Should we disable Travis for this repo or create a basic Travis config for it?

**Comment by gnestor** [comment]
@jasongrout I'd like to get this merged but I don't know how to configure or disable Travis for this repo. Can you help?

**Comment by blink1073** [comment]
@gnestor, I disabled it on Travis and added you to the committers team on the org.

**Comment by gnestor** [comment]
Thanks @blink1073!

**Pull request merged**
